os: linux
dist: xenial

sudo: required

addons:
  apt:
    packages:
      - cpanminus
      - build-essential
      - libncurses5-dev
      - libpcre3-dev
      - libreadline-dev
      - libssl-dev
      - perl

cache:
  directories:
    - download-cache

env:
  global:
    - JOBS=2
    - OPENRESTY_PREFIX=/usr/local/openresty

install:
  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - sudo apt-get install openresty
  - git clone https://github.com/openresty/test-nginx.git test-nginx

script:
  - cd test-nginx && (sudo cpanm . > build.log 2>&1 || (cat build.log && exit 1)) && cd ..
  - export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
  - make test
